name: my_flutter_hammer
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  slide_countdown: ^1.5.2
  # flutter_image_slideshow: ^0.1.6
  video_player: ^2.8.3
  dio: ^5.4.1
  # flutter_splash_screen: ^3.0.0
  chewie: ^1.7.5
  provider: ^6.0.5
  flutter_swiper_view: ^1.1.8
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  scoped_model: ^2.0.0
  http: ^1.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  http_parser: ^4.0.2
  fluro: ^2.0.5
  # flutter_html: ^1.0.2
  flutter_screenutil: ^5.9.0
  # flutter_web: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  generate: true
    # - assets/beard.jpeg
    # - assets/sit.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
